# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Show me the code!
author:
  name: Prabhakar Kumar

description: >- # this means to ignore newlines until "baseurl:"
  Talk is cheap, show me the code!

google_analytics: UA-20481925-1
adsense_enabled: false

# Disqus Comments
disqus:
  shortname: techbite


plugins:
  - jekyll-feed
  - jekyll-youtube
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-gist
  - jekyll-sitemap

theme: minima

minima:
  social_links:
    - {platform: github, user_url: https://github.com/prabhakar97}
    - {platform: mastodon, user_url: https://toot.techbeat.in/@prab97}


jekyll-archives:
  enabled: ['tags']
  layout: archive
  permalinks:
    tag: '/tag/:name/'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      sitemap: true
      comments: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
